server:
  port: 8080

spring:

  # 샘플 데이터 설정
  profiles:
    active: local

  # file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # Swagger
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # Session
  session:
    store-type: jdbc

  config:
    import:
      - classpath:/real-application.yml


logging:

  file:
    name: ${user.dir}/log/event-check.log
    max-history: 7
    max-size: 10MB


